### ISSUE TITLE
Can not play input ts file

### ISSUE THREAD

**Issue by papachappa** [Barracuda09/SATPI#53] opened 2017-04-24 15:47 UTC
Hello and greeting!
Found your satpi utility on github. But could you please help me. I am trying to input TS File on satip and then play him stream via vlc in ubuntu machine.
As i understand satpi can input ts files, so i run server, then in terminal i typed 
 
vlc http://ipwhereserverrun:8875/?msys=file&uri=/path/to/test.ts

In web frontend status i can see in Stream info Session ID and IP of the stream. Then i try to play my ts file on the same machine:
vlc http://ipwhereserverrun:8875/?msys=dvbs&freq=2003&pids=0,851
But vlc return error "Open of http://ipwhereserverrun:8875/?msys=dvbs&freq=2003&pids=0,851 failed"
What am i doing wrong? Please help.

**Comment by Barracuda09** [comment] 2017-04-28 06:57
Hi,

At first sorry for the late reply, and thanks for trying SatPI.

The first question:
``vlc http://ipwhereserverrun:8875/?msys=file&uri=/path/to/test.ts``
``The uri is relative to the SatPI bin (At the moment).``

The second:
``vlc http://ipwhereserverrun:8875/?msys=dvbs&freq=2003&pids=0,851``
I do not know what you are trying to do here, watch a DVB-S channel?

The request is not complete to do this, and it should be something like this (maybe):
``vlc http://ipwhereserverrun:8875/?src=1&freq=11836&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=27500&fec=34&pids=0,851``

You have to specify more parameter to tune.

Regards,

Marc Postema

**Comment by papachappa** [comment] 2017-04-28 09:11
Hello, Marc!
Thank you for your reply. About first question - move mpeg ts file to satpi bin directory and execute "vlc  http://ipoftheserver:8875/?msys=file&uri=Astra1_DVB-S1_12604MHz_hh_22000.ts ". Server sees the stream on frontend 0

Frontend Info
Stream Index 0
Enable
Attached yes
Name TS Reader
Path Astra1_DVB-S1_12604MHz_hh_22000.ts
Stream Info
Owner 172.31.14.154
Session ID 0279714759
RTP packet count 259181
RTP streamed (MB) 325.281
Stream Configuration
RTCP Signal Update Freq
About second question - yes i am trying to get dbv-s channel from that file  Astra1_DVB-S1_12604MHz_hh_22000.ts

I execute "vlc rtsp://ipoftheserver:554/?src=0&freq=12604&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=all"
Error occured 

Then i execute "http://172.31.14.154:8875/?src=0&freq=12604&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=all"
Same error

Logs:
Fri Apr 28 11:59:16.0280 2017  6  --- starting SatPI version: 1.5.191~gf82493a ---
Fri Apr 28 11:59:16.0281 2017  6  Number of processors online: 4
Fri Apr 28 11:59:16.0282 2017  6  Default network buffer size: 104 KBytes
Fri Apr 28 11:59:16.0283 2017  6  enp4s0: 172.31.14.154 [d8:cb:8a:ef:b8:f9]
Fri Apr 28 11:59:16.0284 2017  6  Current DVB_API_VERSION: 5.10
Fri Apr 28 11:59:16.0286 2017  6  Detecting frontends in: /dev/dvb
Fri Apr 28 11:59:16.0286 2017  6  Frontends found: 0
Fri Apr 28 11:59:16.0286 2017  6  Setting up TS Reader using path: .
Fri Apr 28 11:59:16.0288 2017  6  Setting up TS Streamer
Fri Apr 28 11:59:16.0289 2017  6  Setting SSDP annouce interval to: 60 Sec
 Fri Apr 28 11:59:16.0292 2017  6  Setting up SSDP server with BOOTID: 14
 Fri Apr 28 11:59:16.0292 2017  6  Setting up RTSP server
 Fri Apr 28 11:59:16.0292 2017  6  Setting up HTTP server
 Fri Apr 28 11:59:16.2263 2017  6  HTTP Connection from 172.31.14.154 Port 43484 (fd: 8)
 Fri Apr 28 11:59:16.5536 2017  6  HTTP Connection from 172.31.14.138 Port 58843 (fd: 9)
 Fri Apr 28 11:59:16.5714 2017  6  HTTP Connection from 172.31.14.143 Port 43984 (fd: 10)
 Fri Apr 28 11:59:16.5964 2017  6  HTTP Connection from 172.31.14.156 Port 43411 (fd: 11)
 Fri Apr 28 11:59:16.6019 2017  6  HTTP Connection from 172.31.14.150 Port 41529 (fd: 12)
 Fri Apr 28 11:59:18.9743 2017  6  HTTP Connection from 172.31.14.152 Port 51701 (fd: 9)
 Fri Apr 28 11:59:19.6992 2017  6  HTTP Connection from 172.31.14.154 Port 43610 (fd: 10)
 Fri Apr 28 11:59:19.6995 2017  6  HTTP Connection from 172.31.14.154 Port 43612 (fd: 11)
 Fri Apr 28 11:59:19.6995 2017  6  HTTP Connection from 172.31.14.154 Port 43614 (fd: 12)
 Fri Apr 28 11:59:19.6996 2017  6  HTTP Connection from 172.31.14.154 Port 43616 (fd: 13)
 Fri Apr 28 11:59:19.6998 2017  6  HTTP Connection from 172.31.14.154 Port 43618 (fd: 14)
 Fri Apr 28 11:59:35.9698 2017  6  HTTP Connection from 172.31.14.154 Port 44512 (fd: 15)
 Fri Apr 28 11:59:35.9714 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0279714759
 Fri Apr 28 11:59:35.9714 2017  6  Stream: 0, StreamClient[0] with SessionID 0279714759 for file
 Fri Apr 28 11:59:35.9715 2017  6  Stream: 0, TS Reader using path: Astra1_DVB-S1_12604MHz_hh_22000.ts
 Fri Apr 28 11:59:35.9715 2017  6  Stream: 0, HTTP set network buffer size: 25650 KBytes
 Fri Apr 28 11:59:35.9716 2017  6  Stream: 0, Start HTTP stream to 172.31.14.154:44512
 Fri Apr 28 11:59:36.2057 2017  6  Stream: 0, PAT - PID 0: sectionLength: 181 tableDataSize: 188
 Fri Apr 28 11:59:36.2080 2017  6  Stream: 0, PAT: Section Length: 181 TID: 1111 Version: 217 secNr: 0 lastSecNr: 0 CRC: 1E363F47
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 0 NIT PID: 0016
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 13 PMT PID: 0032
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7201 PMT PID: 7201
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7203 PMT PID: 7203
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7212 PMT PID: 7212
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7216 PMT PID: 7216
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7230 PMT PID: 7230
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7232 PMT PID: 7232
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7243 PMT PID: 7243
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7248 PMT PID: 7248
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7252 PMT PID: 7252
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7260 PMT PID: 7260
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7263 PMT PID: 7263
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7264 PMT PID: 7264
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7266 PMT PID: 7266
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7267 PMT PID: 7267
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7268 PMT PID: 7268
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7270 PMT PID: 7270
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7276 PMT PID: 7276
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7277 PMT PID: 7277
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7280 PMT PID: 7280
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7281 PMT PID: 7281
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7287 PMT PID: 7287
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7289 PMT PID: 7289
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7290 PMT PID: 7290
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7292 PMT PID: 7292
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7294 PMT PID: 7294
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7295 PMT PID: 7295
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7297 PMT PID: 7297
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7299 PMT PID: 7299
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7302 PMT PID: 7302
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7910 PMT PID: 7910
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7911 PMT PID: 7911
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7920 PMT PID: 0336
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7931 PMT PID: 7931
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28534 PMT PID: 3400
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28535 PMT PID: 3500
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28536 PMT PID: 3600
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28537 PMT PID: 3700
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28544 PMT PID: 5600
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28545 PMT PID: 5610
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28546 PMT PID: 5620
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28547 PMT PID: 5630
 Fri Apr 28 11:59:36.3729 2017  6  Stream: 0, PMT - PID 32: sectionLength: 18 tableDataSize: 188
 Fri Apr 28 11:59:36.3729 2017  6  Stream: 0, PMT - Section Length: 18 Prog NR: 13 Version: 195 secNr: 0 lastSecNr: 0 PCR-PID: 8191 Program Length: 0 CRC: A5D32C6B
 Fri Apr 28 11:59:36.3729 2017  6  Stream: 0, PMT Found: 0032 with PCR: 8191
Fri Apr 28 11:58:17.7842 2017  6  HTTP Connection from 172.31.14.154 Port 41690 (fd: 14)
Fri Apr 28 11:58:17.7855 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0266144818
Fri Apr 28 11:58:17.7855 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 11:58:17.7855 2017  3  Found no Stream/Client of interest!
Fri Apr 28 11:58:17.7865 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
Fri Apr 28 11:58:17.8206 2017  6  HTTP Connection from 172.31.14.154 Port 41700 (fd: 14)
Fri Apr 28 11:58:17.8218 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0258172921
Fri Apr 28 11:58:17.8218 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 11:58:17.8218 2017  3  Found no Stream/Client of interest!
Fri Apr 28 11:58:17.8227 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1

Fri Apr 28 12:08:34.8954 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 12:08:34.8954 2017  3  Found no Stream/Client of interest!
Fri Apr 28 12:08:34.8956 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0256267502
Fri Apr 28 12:08:34.8956 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 12:08:34.8956 2017  3  Found no Stream/Client of interest!
Fri Apr 28 12:08:34.8956 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
Fri Apr 28 12:08:34.8963 2017  6  RTSP Connection from 172.31.14.154 Port 38014 (fd: 9)
Fri Apr 28 12:08:34.8980 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
Fri Apr 28 12:08:34.9082 2017  6  RTSP Connection from 172.31.14.154 Port 38018 (fd: 9)
Fri Apr 28 12:08:34.9112 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0280160960
 Fri Apr 28 12:08:34.9112 2017  6  Stream: 1, Not capable of handling msys=dvbs
 Fri Apr 28 12:08:34.9113 2017  3  Found no Stream/Client of interest!
 Fri Apr 28 12:08:34.9121 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0259263483
 Fri Apr 28 12:08:34.9122 2017  6  Stream: 1, Not capable of handling msys=dvbs
 Fri Apr 28 12:08:34.9122 2017  3  Found no Stream/Client of interest!
 Fri Apr 28 12:08:34.9131 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
 Fri Apr 28 12:08:34.9138 2017  6  RTSP Connection from 172.31.14.154 Port 38026 (fd: 9)
 Fri Apr 28 12:08:34.9157 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
 Fri Apr 28 12:08:34.9191 2017  6  RTSP Connection from 172.31.14.154 Port 38028 (fd: 9)
 Fri Apr 28 12:08:34.9192 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0258257498

Could you please help me, what am i doing wrong?

**Comment by papachappa** [comment] 2017-04-28 09:12
Hello, Marc!
Thank you for your reply. About first question - move mpeg ts file to satpi bin directory and execute "vlc http://ipoftheserver:8875/?msys=file&uri=Astra1_DVB-S1_12604MHz_hh_22000.ts". Server sees the stream on frontend 0

Frontend Info
Stream Index	0
Enable	
Attached	yes
Name	TS Reader
Path	Astra1_DVB-S1_12604MHz_hh_22000.ts
Stream Info
Owner	172.31.14.154
Session ID	0279714759
RTP packet count	259181
RTP streamed (MB)	325.281
Stream Configuration
RTCP Signal Update Freq	
1

About second question - yes i am trying to get dbv-s channel from that file Astra1_DVB-S1_12604MHz_hh_22000.ts

I execute "vlc rtsp://ipoftheserver:554/?src=0&freq=12604&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=all"
Error occured 

Then i execute "http://172.31.14.154:8875/?src=0&freq=12604&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=all"
Same error

Logs:
Fri Apr 28 11:59:16.0280 2017  6  --- starting SatPI version: 1.5.191~gf82493a ---
Fri Apr 28 11:59:16.0281 2017  6  Number of processors online: 4
Fri Apr 28 11:59:16.0282 2017  6  Default network buffer size: 104 KBytes
Fri Apr 28 11:59:16.0283 2017  6  enp4s0: 172.31.14.154 [d8:cb:8a:ef:b8:f9]
Fri Apr 28 11:59:16.0284 2017  6  Current DVB_API_VERSION: 5.10
Fri Apr 28 11:59:16.0286 2017  6  Detecting frontends in: /dev/dvb
Fri Apr 28 11:59:16.0286 2017  6  Frontends found: 0
Fri Apr 28 11:59:16.0286 2017  6  Setting up TS Reader using path: .
Fri Apr 28 11:59:16.0288 2017  6  Setting up TS Streamer
Fri Apr 28 11:59:16.0289 2017  6  Setting SSDP annouce interval to: 60 Sec
 Fri Apr 28 11:59:16.0292 2017  6  Setting up SSDP server with BOOTID: 14
 Fri Apr 28 11:59:16.0292 2017  6  Setting up RTSP server
 Fri Apr 28 11:59:16.0292 2017  6  Setting up HTTP server
 Fri Apr 28 11:59:16.2263 2017  6  HTTP Connection from 172.31.14.154 Port 43484 (fd: 8)
 Fri Apr 28 11:59:16.5536 2017  6  HTTP Connection from 172.31.14.138 Port 58843 (fd: 9)
 Fri Apr 28 11:59:16.5714 2017  6  HTTP Connection from 172.31.14.143 Port 43984 (fd: 10)
 Fri Apr 28 11:59:16.5964 2017  6  HTTP Connection from 172.31.14.156 Port 43411 (fd: 11)
 Fri Apr 28 11:59:16.6019 2017  6  HTTP Connection from 172.31.14.150 Port 41529 (fd: 12)
 Fri Apr 28 11:59:18.9743 2017  6  HTTP Connection from 172.31.14.152 Port 51701 (fd: 9)
 Fri Apr 28 11:59:19.6992 2017  6  HTTP Connection from 172.31.14.154 Port 43610 (fd: 10)
 Fri Apr 28 11:59:19.6995 2017  6  HTTP Connection from 172.31.14.154 Port 43612 (fd: 11)
 Fri Apr 28 11:59:19.6995 2017  6  HTTP Connection from 172.31.14.154 Port 43614 (fd: 12)
 Fri Apr 28 11:59:19.6996 2017  6  HTTP Connection from 172.31.14.154 Port 43616 (fd: 13)
 Fri Apr 28 11:59:19.6998 2017  6  HTTP Connection from 172.31.14.154 Port 43618 (fd: 14)
 Fri Apr 28 11:59:35.9698 2017  6  HTTP Connection from 172.31.14.154 Port 44512 (fd: 15)
 Fri Apr 28 11:59:35.9714 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0279714759
 Fri Apr 28 11:59:35.9714 2017  6  Stream: 0, StreamClient[0] with SessionID 0279714759 for file
 Fri Apr 28 11:59:35.9715 2017  6  Stream: 0, TS Reader using path: Astra1_DVB-S1_12604MHz_hh_22000.ts
 Fri Apr 28 11:59:35.9715 2017  6  Stream: 0, HTTP set network buffer size: 25650 KBytes
 Fri Apr 28 11:59:35.9716 2017  6  Stream: 0, Start HTTP stream to 172.31.14.154:44512
 Fri Apr 28 11:59:36.2057 2017  6  Stream: 0, PAT - PID 0: sectionLength: 181 tableDataSize: 188
 Fri Apr 28 11:59:36.2080 2017  6  Stream: 0, PAT: Section Length: 181 TID: 1111 Version: 217 secNr: 0 lastSecNr: 0 CRC: 1E363F47
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 0 NIT PID: 0016
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 13 PMT PID: 0032
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7201 PMT PID: 7201
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7203 PMT PID: 7203
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7212 PMT PID: 7212
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7216 PMT PID: 7216
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7230 PMT PID: 7230
 Fri Apr 28 11:59:36.2081 2017  6  Stream: 0, PAT: Prog NR: 7232 PMT PID: 7232
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7243 PMT PID: 7243
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7248 PMT PID: 7248
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7252 PMT PID: 7252
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7260 PMT PID: 7260
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7263 PMT PID: 7263
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7264 PMT PID: 7264
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7266 PMT PID: 7266
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7267 PMT PID: 7267
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7268 PMT PID: 7268
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7270 PMT PID: 7270
 Fri Apr 28 11:59:36.2082 2017  6  Stream: 0, PAT: Prog NR: 7276 PMT PID: 7276
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7277 PMT PID: 7277
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7280 PMT PID: 7280
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7281 PMT PID: 7281
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7287 PMT PID: 7287
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7289 PMT PID: 7289
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7290 PMT PID: 7290
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7292 PMT PID: 7292
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7294 PMT PID: 7294
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7295 PMT PID: 7295
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7297 PMT PID: 7297
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7299 PMT PID: 7299
 Fri Apr 28 11:59:36.2083 2017  6  Stream: 0, PAT: Prog NR: 7302 PMT PID: 7302
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7910 PMT PID: 7910
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7911 PMT PID: 7911
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7920 PMT PID: 0336
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 7931 PMT PID: 7931
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28534 PMT PID: 3400
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28535 PMT PID: 3500
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28536 PMT PID: 3600
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28537 PMT PID: 3700
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28544 PMT PID: 5600
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28545 PMT PID: 5610
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28546 PMT PID: 5620
 Fri Apr 28 11:59:36.2084 2017  6  Stream: 0, PAT: Prog NR: 28547 PMT PID: 5630
 Fri Apr 28 11:59:36.3729 2017  6  Stream: 0, PMT - PID 32: sectionLength: 18 tableDataSize: 188
 Fri Apr 28 11:59:36.3729 2017  6  Stream: 0, PMT - Section Length: 18 Prog NR: 13 Version: 195 secNr: 0 lastSecNr: 0 PCR-PID: 8191 Program Length: 0 CRC: A5D32C6B
 Fri Apr 28 11:59:36.3729 2017  6  Stream: 0, PMT Found: 0032 with PCR: 8191

Fri Apr 28 11:58:17.7842 2017  6  HTTP Connection from 172.31.14.154 Port 41690 (fd: 14)
Fri Apr 28 11:58:17.7855 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0266144818
Fri Apr 28 11:58:17.7855 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 11:58:17.7855 2017  3  Found no Stream/Client of interest!
Fri Apr 28 11:58:17.7865 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
Fri Apr 28 11:58:17.8206 2017  6  HTTP Connection from 172.31.14.154 Port 41700 (fd: 14)
Fri Apr 28 11:58:17.8218 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0258172921
Fri Apr 28 11:58:17.8218 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 11:58:17.8218 2017  3  Found no Stream/Client of interest!
Fri Apr 28 11:58:17.8227 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1


Fri Apr 28 12:08:34.8954 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 12:08:34.8954 2017  3  Found no Stream/Client of interest!
Fri Apr 28 12:08:34.8956 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0256267502
Fri Apr 28 12:08:34.8956 2017  6  Stream: 1, Not capable of handling msys=dvbs
Fri Apr 28 12:08:34.8956 2017  3  Found no Stream/Client of interest!
Fri Apr 28 12:08:34.8956 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
Fri Apr 28 12:08:34.8963 2017  6  RTSP Connection from 172.31.14.154 Port 38014 (fd: 9)
Fri Apr 28 12:08:34.8980 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
Fri Apr 28 12:08:34.9082 2017  6  RTSP Connection from 172.31.14.154 Port 38018 (fd: 9)
Fri Apr 28 12:08:34.9112 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0280160960
 Fri Apr 28 12:08:34.9112 2017  6  Stream: 1, Not capable of handling msys=dvbs
 Fri Apr 28 12:08:34.9113 2017  3  Found no Stream/Client of interest!
 Fri Apr 28 12:08:34.9121 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0259263483
 Fri Apr 28 12:08:34.9122 2017  6  Stream: 1, Not capable of handling msys=dvbs
 Fri Apr 28 12:08:34.9122 2017  3  Found no Stream/Client of interest!
 Fri Apr 28 12:08:34.9131 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
 Fri Apr 28 12:08:34.9138 2017  6  RTSP Connection from 172.31.14.154 Port 38026 (fd: 9)
 Fri Apr 28 12:08:34.9157 2017  6  Stream: 0, Close StreamClient[0] with SessionID -1
 Fri Apr 28 12:08:34.9191 2017  6  RTSP Connection from 172.31.14.154 Port 38028 (fd: 9)
 Fri Apr 28 12:08:34.9192 2017  6  Found StreamID x - SessionID x - Creating new SessionID: 0258257498

Could you please help me, what am i doing wrong?

**Comment by Barracuda09** [comment] 2017-04-28 09:30
Hi,

I think I know were the problem is.
You stream the TS file and then you have to 'select' an program in VLC.
The example I added was for if you have DVB-S tuners in you server.

But I have not done this, I only 'record' one program and view it.

**Comment by papachappa** [comment] 2017-04-28 11:09
So, is it possible to input ts file(with different programs) with vlc and get or play stream(ts file) from satpi server with also vlc?

**Comment by papachappa** [comment] 2017-04-28 11:10
So, is it possible to input ts file(with different programs) with vlc and get or play stream(ts file) from satpi server with also vlc?

**Comment by Barracuda09** [comment] 2017-04-28 11:21
I am not sure about that (never tried it myself)

It is possible to let SatPI 'stream' an TS file (With one program) to VLC

**Comment by papachappa** [comment] 2017-04-28 11:50
But, satpi can input ts file as TSReader, therefore we can play via vlc somehow?

**Comment by Barracuda09** [comment] 2017-04-28 11:55
Yes it should be possible with this example:
``http://ip.of.your.box:8875/?msys=file&uri=test.ts``

This will show the program in VLC (if you open it as an network stream)

**Comment by papachappa** [comment] 2017-04-28 12:04
In other words, can we emulate situation? On the input satPI takes some ts file(dvb-s), transforms it to dbv-s standard and vlc as a client can read it like http://satipserver:8875/?src=0&freq=12604&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=0,5100,5101,5102,5103,5104,5105,5106

**Comment by Barracuda09** [comment] 2017-04-28 12:13
I don't think it is very useful to do it like this.
maybe add only 'pids=0,2,18...' to this request:
``http://ip.of.your.box:8875/?msys=file&uri=test.ts``
to 'select' the program. But within VLC it should be able to do that as well.

**Comment by papachappa** [comment] 2017-04-28 12:53
Am i correct that if we have some test.ts file with one program, then send to satpi server via vlc like http://ip.of.your.box:8875/?msys=file&uri=test.ts, then we can get the stream from satpi server and play him like http://ip.of.your.box:8875/?src=0&freq=12604&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=0,5100,5101,5102,5103,5104,5105,5106
??

**Comment by Barracuda09** [comment] 2017-04-29 19:17
No it works like this, on the SatPI server is the test.ts (which you record) this can be send/stream to VLC
with ``http://ip.of.your.box:8875/?msys=file&uri=test.ts``

**Comment by lars18th** [comment] 2017-06-30 15:45
Hi,

I'm not sure what like to do @papachappa ...

But I feel hi wants to "remap" the call with "&msys=dvbs&freq=12604&pol=h&ro=0.35&mtype=qpsk&plts=off&sr=22000&fec=56" 
to "msys=file&uri=test.ts"
So when the first commes then it's processed as the second.

I'm right?
Perhaps it's not very complicated to do it (internal map of input files to some frequencies).

**Comment by Barracuda09** [comment] 2017-10-12 10:36
Hi @papachappa 

I think @lars18th  has it correct, I misunderstood your question.

The Translation of this request is not implemented  at the moment for TSReader.
It is for DVB-S to DVB-C (Or at least in the funtion: bool Frontend::capableToTransform(const std::string &msg, const std::string &method) const )

This can be done for TSReader as well.

**Comment by lars18th** [comment] 2017-10-13 07:00
Hi @Barracuda09 ,

> This can be done for TSReader as well.

You say that the frequency Translation will be enhanced to other sources (like files)? Great!

Thank you for this great project!

**Comment by lars18th** [comment] 2019-11-20 10:30
Hi @Barracuda09 ,

I feel this issue is already fixed. So please can you close it?
Thank you!

**Comment by Barracuda09** [comment] 2019-11-20 13:17
As requested by @lars18th

**Closed by Barracuda09** 2019-11-20 13:17 UTC
Labels: Fixed, Testers Wanted, enhancement
